mysite/accounts/urls.py
from django.urls import path, include
from .import views

app_name='accounts'

urlpatterns = [
    path('signup/',views.signup_view,name='signup')
]

mysite/articles/urls.py
from django.urls import path
from .import views

app_name ='articles'

urlpatterns = [
    path("",views.article_list, name='list'),
    path("<slug:slug>/", views.article_detail, name='detail'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from .import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('articles/', include('articles.urls')),
    path('about/',views.about),
    path("",views.homepage),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

mysite/accounts/models.py
from django.db import models

# Create your models here.

mysite/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
     title = models.CharField(max_length=100)
     slug = models.SlugField()
     body = models.TextField()
     date = models.DateTimeField(auto_now_add=True)
     thumb = models.ImageField(default='default.png',blank=True)
     # add in author later

     def __str__(self):
          return self.title

     def snippet(self):
          return self.body[0:50] + '...'

mysite/accounts/views.py
from django.shortcuts import render

# Create your views here.
def signup_view(request):
    return render(request,'accounts/signup.html')

mysite/articles/views.py
from django.shortcuts import render
from .models import Article
from django.http import HttpResponse

def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request,'articles/article_list.html',{'articles': articles})

def article_detail(request,slug):
    # return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(request,'articles/article_detail.html',{'article':article })

mysite/mysite/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    return render(request,'homepage.html')

def about(request):
    return render(request,'about.html')

mysite/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Signup</h1>
{% endblock %}

mysite/articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="'article-detail">
    <div class="article">
        <img src="{{ article.thumb.url }}"/>
        <h2>{{ article.title }}</h2>
        <p>{{ article.body }}</p>
        <p>{{ article.date }}</p>
    </div>
</div>


{% endblock %}

mysite/articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Articles List</h1>
    <div class="articles">
        {% for article in articles %}
            <div class="article">
                <h2><a href="{% url 'articles:detail' slug=article.slug %}"> {{article.title}}</a></h2>
                <p>{{article.snippet}}</p>
                <p>{{article.date}}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

mysite/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
</head>
<body>
    <h1>About us</h1>
    <p>We like django.</p>
</body>
</html>

mysite/templates/base_layout.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Articles</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>
<body>
    <div class="wrapper">
        <h1><a href="{% url 'articles:list' %}"><img src ="{% static 'images.png' %}"/></a></h1>
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

mysite/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Homepage</title>
</head>
<body>
    <h1>This is the homepage </h1>
    <p>Welcome to Djangonautic</p>
</body>
</html>